### ISSUE TITLE
Fix: Axis manipulation

### ISSUE THREAD

**Issue by ykyyky001** [TOBgit/MaterialPlot#18]
Axis select tab: when one of the properties is without _mean and _sd, but just a simple value (e.g. density), it doesn't work.
Now the user needs to plot something(materials or family bubble) to refresh the plot.
I added a refresh plot button on the tab, so users can see if their syntax input is in effect.

**Comment by TienanLi** [comment]
1) simple value column handling is fixed by  [76da6ad](https://github.com/TOBgit/MaterialPlot/commit/76da6ad3166a68ee25bf88be7fda1a622261d21c)

2) could you link the refresh plot button to the func onClickGenPropChrt()? @ykyyky001 That should resolve your second request. But I don't know the name of the refresh plot button.
